### ISSUE TITLE
Icons are not displayed

### ISSUE THREAD

**Issue by aernda** [ekho/redmine_subtask_list_enhanced#1] opened 2020-04-17 10:03 UTC
We are using Redmine 4.1.0. The installation worked fine. But unfortunately the icons are not displayed.

![plugin](https://user-images.githubusercontent.com/29729716/79557634-3080e680-80a3-11ea-908b-eadf3fb5bfbe.png)

**Comment by MasyGreen** [comment] 2020-04-17 10:16
I don`t have this probelm. All work fine. But where you get the button "Hide close issues"? it`s addition plugin?

**Comment by aernda** [comment] 2020-05-14 19:16
No, it isn't an additional plugin ...
![image002](https://user-images.githubusercontent.com/29729716/81975374-34167780-9627-11ea-8607-8cd6adbd3117.png)
 
This button was my main reason to try out this plugin. ;-)

**Comment by merryech0** [comment] 2020-05-14 19:27
@aernda This button was my main reason to write this plugin ;-)

**Comment by merryech0** [comment] 2020-05-14 22:38
@aernda could you profile page loading ? May be some problems with reverse proxy or other?

Plugin already contains all needed fonts and styles.

**Comment by veshus** [comment] 2020-07-02 07:59
+1
I have the same problem.
As I can see in the debugger, the problem is in the [font-awesome.min.css](https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css) with 
`.fa-eye-slash:before {
 content:"\f070"
}`

Page profile log shows HTTP200 on all links.

**Comment by ashrafalzyoud** [comment] 2020-08-24 23:46
same problem any soultion yet???
@ekho 
@MasyGreen 
@aernda 
@veshus

**Comment by MasyGreen** [comment] 2020-08-25 06:03
> same problem any soultion yet???
> @MasyGreen
no(

**Comment by iprok** [comment] 2020-09-11 14:36
I also have the same problem. And it seems for me that is because I'm using [additionals](https://github.com/AlphaNodes/additionals) plugin that loads its own version of fontawesome css.

Guys that have the problem, do you have addtitionals plugin enabled?

**Comment by ashrafalzyoud** [comment] 2020-09-11 14:38
no i dont have it

**Comment by iprok** [comment] 2020-09-11 14:41
@ashrafalzyoud open page source of the page with the issue when you see the problem. Try to search it for 'fontawesome'. How many css files are you able to find there?

**Comment by ashrafalzyoud** [comment] 2020-09-11 15:15
i have only one in my page sourece
<link rel="stylesheet" media="screen" href="/plugin_assets/redmine_subtask_list_enhanced/stylesheets/fontawesome.min.css?1599836920" /><link rel="stylesheet" media="screen" href="/plugin_assets/redmine_subtask_list_enhanced/stylesheets/subtask_tree_table.css?1599204365" /><script src="/plugin_assets/redmine_subtask_list_enhanced/javascripts/jquery-simple-tree-table.js?1599204365"></script><script src="/plugin_assets/redmine_subtask_list_enhanced/javascripts/subtask_tree_table.js?1599204365"></script><link rel="stylesheet" media="screen" href="/plugin_assets/redmine_subtask_list_enhanced/stylesheets/subtask_closed_toggle.css?1599204365" /><script src="/plugin_assets/redmine_subtask_list_enhanced/javascripts/subtask_closed_toggle.js?1599204365"></script><script src="/javascripts/jstoolbar/jstoolbar.js?1590810736"></script><script src="/javascripts/jstoolbar/lang/jstoolbar-en.js?1590810736"></script><link rel="stylesheet" media="screen" href="/stylesheets/jstoolbar.css?1590810736" /><script>

**Comment by ashrafalzyoud** [comment] 2020-09-11 15:16
just one css file
<link rel="stylesheet" media="screen" href="/plugin_assets/redmine_subtask_list_enhanced/stylesheets/fontawesome.min.css?1599836920" /><link rel="stylesheet" media="screen" href="/plugin_assets/redmine_subtask_list_enhanced/stylesheets/subtask_tree_table.css?1599204365" /><script src="/plugin_assets/redmine_subtask_list_enhanced/javascripts/jquery-simple-tree-table.js?1599204365"></script><script src="/plugin_assets/redmine_subtask_list_enhanced/javascripts/subtask_tree_table.js?1599204365"></script><link rel="stylesheet" media="screen" href="/plugin_assets/redmine_subtask_list_enhanced/stylesheets/subtask_closed_toggle.css?1599204365" /><script src="/plugin_assets/redmine_subtask_list_enhanced/javascripts/subtask_closed_toggle.js?1599204365"></script><script src="/javascripts/jstoolbar/jstoolbar.js?1590810736"></script><script src="/javascripts/jstoolbar/lang/jstoolbar-en.js?1590810736"></script><link rel="stylesheet" media="screen" href="/stylesheets/jstoolbar.css?1590810736" /><script>

**Comment by iprok** [comment] 2020-09-11 15:57
I've fixed this in #2 . Please merge

P.S. Огромное спасибо за плагин.

**Comment by merryech0** [comment] 2020-09-11 16:09
Merged

P.S. Да не за что) Спасибо за фикс)

**Closed as completed** 2020-09-11 16:08 UTC

**Comment by ashrafalzyoud** [comment] 2020-09-11 16:24
expand all + collpase all  + hide close issue
not appear

**Comment by ashrafalzyoud** [comment] 2020-09-11 16:24
@iprok

**Comment by ashrafalzyoud** [comment] 2020-09-11 16:28
perfect its work

**Comment by aernda** [comment] 2020-09-11 16:46
Thanks!
